// File generated by FlutterFire CLI & customized for AutoDealers India.
// To connect to your live Firebase project:
// 1. Run: `flutterfire configure` OR
// 2. Replace the placeholder apiKey, appId, and projectId below with your Firebase Web/Android credentials.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoPlaceholderKeyForFlutterAutoDealers',
    appId: '1:1234567890:web:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'autodealers-india-demo',
    authDomain: 'autodealers-india-demo.firebaseapp.com',
    storageBucket: 'autodealers-india-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoPlaceholderKeyForFlutterAutoDealers',
    appId: '1:1234567890:android:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'autodealers-india-demo',
    storageBucket: 'autodealers-india-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoPlaceholderKeyForFlutterAutoDealers',
    appId: '1:1234567890:ios:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'autodealers-india-demo',
    storageBucket: 'autodealers-india-demo.appspot.com',
    iosBundleId: 'com.cardealer.saas',
  );
}
